address: '0.0.0.0:8080'       # self TCP-Server ip:port address where API service will be alvalible
web-address: '0.0.0.0:8081'   # self Web-Socket ip:port address where API service will be alvalible
logging:
    level: debug               # logging level info/debug/trace, default info
services:                      # list of currently avalible API services
    - crane_data_server:
        name: 'crane_data_server'
        type: postgres
        path: 'localhost:5432'
        user: crane_data_server
        pass: 00d0-25e4-*&s2-ccds  
