FROM rust:1.74 as builder
RUN apt update
WORKDIR /app
COPY src ./src
COPY Cargo.lock Cargo.toml ./
# compile the application binary executable
RUN cargo build --release

FROM debian:12.2 as packager
RUN apt update && apt install -y --no-install-recommends \
	&& apt install -y \
		build-essential \
		devscripts
WORKDIR /package
COPY --from=builder /app/target/release/api-server ./
COPY package_deb.sh config.yaml database.sqlite database22.sqlite ./
# test deb packaging in isolated environment
CMD /bin/bash
