version: "3.0"

networks:
  api-server:

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=sss-computing
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/:/sql/
    networks:
      - api-server

  api:
    build: .
    ports:
      - 8080:8080
    networks:
      - api-server
