DROP TABLE IF EXISTS port;

CREATE TABLE port (
    id INT GENERATED ALWAYS AS IDENTITY,
    port_name_ru TEXT NOT NULL,
    port_name_en TEXT NOT NULL,
    port_code TEXT NOT NULL,
    CONSTRAINT port_pk PRIMARY KEY (id),
    CONSTRAINT port_name_ru_length_check CHECK (char_length(port_name_ru) > 0),
    CONSTRAINT port_name_en_length_check CHECK (char_length(port_name_en) > 0),
    CONSTRAINT port_code_length_check CHECK (char_length(port_code) = 5),
    CONSTRAINT port_code_unique UNIQUE (port_code)
);

-- Temporary fake data
INSERT INTO
    port (port_name_ru, port_name_en, port_code)
VALUES
    ('Архангельск','Arkhangelsk','RUARH'),
    ('Азов','Azov','RUAZO'),
    ('Бронка','Bronka','RUBNK'),
    ('Калининград','Kaliningrad','RUKGD'),
    ('Новороссийск','Novorossiysk','RUNVS'),
    ('Санкт-Петербург','St Petersburg','RULED'),
    ('Таганрог','Taganrog','RUTAG'),
    ('Усть-Луга','Ust-Luga','RUULU'),
    ('Владивосток','Vladivostok','RUVVO'),
    ('Порт Восточный','Vostochniy, Port','RUVYP'),
    ('Абердин','Aberdeen','USAPG'),
    ('Бальбоа','Balboa','USBAZ'),
    ('Бомонт','Beaumont','USBPT'),
    ('Бриджпорт','Bridgeport','USBDR'),
    ('Корпус-Кристи','Corpus Christi','USCRP'),
    ('Дарроу','Darrow','USDRR'),
    ('Эверетт','Everett','USEVT'),
    ('Фрипорт','Freeport','USFEP'),
    ('Грамерси','Gramercy','USGRY'),
    ('Хило','Hilo','USITO'),
    ('Гонолулу','Honolulu','USHNL'),
    ('Хьюстон','Houston','USHQN'),
    ('Кенаи','Kenai','USENA'),
    ('Лас Вегас','Las Vegas','USLAS'),
    ('Лонг-Бич','Long Beach','USLGB'),
    ('Лонгвью','Longview','USLOG'),
    ('Лос-Анджелес','Los Angeles','USLAX'),
    ('Мобайл','Mobile','USMOB'),
    ('Морхед-Сити','Morehead City','USMRH'),
    ('Новый Орлеан','New Orleans','USMSY'),
    ('Норфолк','Norfolk','USNFK'),
    ('Окленд','Oakland','USOAK'),
    ('Педро','Pedro Bay','USPDB'),
    ('Пуант а-ля Хаче','Pointe a la Hache','USPHC'),
    ('Порт-Хьюнеми','Port Hueneme','USNTD'),
    ('Порт Манати','Port Manatee','USPME'),
    ('Сан-Диего','San Diego','USSAN'),
    ('Саванна','Savannah','USSAV'),
    ('Сиэтл','Seattle','USSEA'),
    ('Санни Поинт','Sunny Point','USSUT'),
    ('Тампа','Tampa','USTPA'),
    ('Уилмингтон','Wilmington','USWTN'),
    ('Аделаида','Adelaide','AUADL'),
    ('Олбани','Albany','AUALH'),
    ('Остров Барроу','Barrow Island','AUBWB'),
    ('Бел-Бей','Bell Bay','AUBEL'),
    ('Ботани-Бей','Botany Bay','AUBTB'),
    ('Брисбен','Brisbane','AUBNE'),
    ('Брум','Broome','AUBME'),
    ('Бенбери','Bunbury','AUBUY'),
    ('Бундеберг','Bundaberg','AUDBB'),
    ('Берни','Burnie','AUBWT'),
    ('Кэрнс','Cairns','AUCNS'),
    ('Коффс-Харбор','Coffs Harbour','AUCFS'),
    ('Дэйлримпл Ислет','Dalrymple Islet','AUDIT'),
    ('Дампьер','Dampier','AUDAM'),
    ('Дарвин','Darwin','AUDRW'),
    ('Девонпорт','Devonport','AUDPO'),
    ('Иден','Eden','AUQDN'),
    ('Эсперанс','Esperance','AUEPR'),
    ('Фримантл','Fremantle','AUFRE'),
    ('Джилонг','Geelong','AUGEX'),
    ('Джералдтон','Geraldton','AUGET'),
    ('Гледстоун','Gladstone','AUGLT'),
    ('Гоув','Gove','AUGOV'),
    ('Гастингс','Hastings','AUHAS'),
    ('Хейпоинт','Haypoint','AUHPT'),
    ('Хобарт','Hobart','AUHBA'),
    ('Курнел','Kurnell','AUKUR'),
    ('Лорд Хов Из','Kwinana','AUKWI'),
    ('Лонсестон','Launceston','AULST'),
    ('Лорд Из','Lord Howe Is','AULDH'),
    ('Маккей','Mackay','AUMKY'),
    ('Остров Маккуори (Антарктида)','Macquarie Island (Antarctica)','AUMQI'),
    ('Мельбурн','Melbourne','AUMEL'),
    ('Мунба','Moomba','AUMOO'),
    ('Ньюкасл','Newcastle','AUNTL'),
    ('Поинт Генри Пир/Мельбурн','Point Henry Pier/Melbourne','AUPHP'),
    ('Порт Ботани','Port Botany','AUPBT'),
    ('Порт Джайлс','Port Giles','AUPGI'),
    ('Порт Кембла','Port Kembla','AUPKL'),
    ('Порт Линкольн','Port Lincoln','AUPLO'),
    ('Порт Пири','Port Pirie','AUPPI'),
    ('Порт Станвак','Port Stanvac','AUPST'),
    ('Портленд','Portland','AUPTJ'),
    ('Рисдон','Risdon','AURDN'),
    ('Сидней','Sydney','AUSYD'),
    ('Тевенард','Thevenard','AUTHE'),
    ('Таунсвилл','Townsville','AUTSV'),
    ('Варанус','Varanus Island','AUVAR'),
    ('Волару','Wallaroo','AUWAL'),
    ('Вестернпоинт','Westernport','AUWEP'),
    ('Уайалла','Whyalla','AUWYA'),
    ('Нефтяная платформа Вуллибутт','Woollybutt Oil Platform','AUWBT'),
    ('Ямба','Yamba','AUYBA'),
    ('Бахрейн','Bahrain','BHBAH'),
    ('Читтагонг','Chittagong','BDCGP'),
    ('Антверпен','Antwerp','BEANR'),
    ('Зеебрюгге','Zeebrugge','BEZEE'),
    ('Сао Франсиско до Сул','São Francisco do Sul','BRSFS'),
    ('Муара','Muara','BNMUA'),
    ('Сирия','Seria','BNSER'),
    ('Чемайнус','Chemainus','CACHM'),
    ('Суррей','Surrey','CASUY'),
    ('Ванкувер','Vancouver','CAVAN'),
    ('Антофагаста','Antofagasta','CLANF'),
    ('Пунта-Аренас','Punta Arenas','CLPUQ'),
    ('Вальпараисо','Valparaiso','CLVAP'),
    ('Картахена','Cartagena','COCTG'),
    ('Аитутаки','Aitutaki','CKAIT'),
    ('Раротонга','Rarotonga','CKRAR'),
    ('Кальдера','Caldera','CRCAL'),
    ('Гуаякиль','Guayaquil','ECEGY'),
    ('Манта','Manta','ECMEC'),
    ('Пуэрто Боливар','Puerto Bolívar','ECPBO'),
    ('Эль Суэц','El Suweis (Suez)','EGSUZ'),
    ('Порт-Саид','Port Said','EGPSD'),
    ('Лабаза','Labasa','FJLBS'),
    ('Лаутока','Lautoka','FJLTK'),
    ('Савусаву','Savusavu','FJSVU'),
    ('Сува','Suva','FJSUV'),
    ('Бора-Бора','Bora-Bora','PFBOB'),
    ('Муреа','Moorea','PFMOZ'),
    ('Папеэте','Papeete','PFPPT'),
    ('Раиатеа','Raiatea','PFRFP'),
    ('Бремен','Bremen','DEBRE'),
    ('Бремерхафен','Bremerhaven','DEBRV'),
    ('Гамбург','Hamburg','DEHAM'),
    ('Апра (Аганья)','Apra (Agana)','GUAPR'),
    ('Гуам','Guam','GUGUM'),
    ('Гонконг','Hong Kong','HKHKG'),
    ('Халдиа','Haldia','INHAL'),
    ('Аданг Бэй','Adang Bay','IDADB'),
    ('Банджармасин','Banjarmasin','IDBDJ'),
    ('Остров Батама','Batam Island','IDBTM'),
    ('Беноа, Бали','Benoa, Bali','IDBOA'),
    ('Битунг, Сулавеси','Bitung, Sulawesi','IDBIT'),
    ('Ботанг','Bontang, Kl','IDBXT'),
    ('Сигадинг','Cigading','IDCIG'),
    ('Джакарта, Ява','Jakarta, Java','IDJKT'),
    ('Касим','Kasim, Ij','IDKAS'),
    ('Макасар','Makassar','IDMAK'),
    ('Самаринда, Калимантан','Samarinda, Kalimantan','IDSRI'),
    ('Терминал Шантан, Kl','Santan Terminal, Kl','IDSAT'),
    ('Терминал Сенипах','Senipah Terminal','IDSPH'),
    ('Сурабайя','Surabaya','IDSUB'),
    ('Танджанг Бара, Kl','Tanjung Bara, Kl','IDTBA'),
    ('Танджунг Приок','Tanjung Priok','IDTPP'),
    ('Бандар Хомеини','Bandar Khomeini','IRBKM'),
    ('Бушехр','Bushehr','IRBUZ'),
    ('Ауниш','Aughinish Island','IEAUG'),
    ('Ашдот','Israel','ILASH'),
    ('Равенна','Ravenna','ITRAN'),
    ('Абурасту','Aburatsu','JPABU'),
    ('Айой','Aioi','JPAIO'),
    ('Акита','Akita','JPAXT'),
    ('Чиба','Chiba','JPCHB'),
    ('Фунабаси','Funabasi','JPFNB'),
    ('Фунагава','Funagawa','JPFNK'),
    ('Гамагори','Gamagori','JPGAM'),
    ('Хатинохе','Hachinohe','JPHHE'),
    ('Хаката/Фукуока','Hakata/Fukuoka','JPHKT'),
    ('Хикошима','Hikoshima','JPHIS'),
    ('Хирохата','Hirohata','JPHRH'),
    ('Хиросима','Hiroshima','JPHIJ'),
    ('Хитачи','Hitachi','JPHTC'),
    ('Имабари','Imabari','JPIMB'),
    ('Имари','Imari','JPIMI'),
    ('Инношима','Innoshima','JPINS'),
    ('Ишиномаки','Ishinomaki','JPISM'),
    ('Ивакуни','Iwakuni','JPIWK'),
    ('Лемишим','Iyomishima','JPIYM'),
    ('Кагосима','Kagoshima','JPKOJ'),
    ('Канда, Фукуока','Kanda, Fukuoka','JPKND'),
    ('Касадо','Kasado','JPKSD'),
    ('Кашима, Ибараки','Kashima, Ibaraki','JPKSM'),
    ('Касукабе','Kasukabe','JPKAK'),
    ('Каваноэ','Kawanoe','JPKWN'),
    ('Кавасаки','Kawasaki','JPKWS'),
    ('Кесеннума','Kesennuma','JPKSN'),
    ('Кимитсу','Kimitsu','JPKMT'),
    ('Кинуура','Kinuura','JPKNU'),
    ('Кобэ','Kobe','JPUKB'),
    ('Коти','Kochi','JPKCZ'),
    ('Коматсшума','Komatsushima','JPKOM'),
    ('Кудаматису','Kudamatsu','JPKUD'),
    ('Куре, Хиросима','Kure, Hiroshima','JPKRE'),
    ('Кусиро','Kushiro','JPKUH'),
    ('Майдзуру','Maizuru','JPMAI'),
    ('Магугаме','Marugame','JPMAR'),
    ('Матисунга','Matsunaga','JPMNG'),
    ('Матсуура, Нагасаки','Matsuura, Nagasaki','JPMTS'),
    ('Мацуяма','Matsuyama','JPMYJ'),
    ('Миике, Фукуока','Miike, Fukuoka','JPMII'),
    ('Мизушима','Mizushima','JPMIZ'),
    ('Нагахама, Шимане','Nagahama, Shimane','JPNAG'),
    ('Нагасаки','Nagasaki','JPNGS'),
    ('Нагоя, Аичи','Nagoya, Aichi','JPNGO'),
    ('Накагусуки','Nakagusuku','JPNAK'),
    ('Намиката','Namikata','JPNIT'),
    ('Нанаймо','Nanaimo','JPNNO'),
    ('Наошима','Naoshima','JPNAS'),
    ('Ниигата','Niigata','JPKIJ'),
    ('Ниихама','Niihama','JPIHA'),
    ('Охшима, Токио','Ohshima, Tokyo','JPOIM'),
    ('Оита','Oita','JPOIT'),
    ('Онохама','Onahama','JPONA'),
    ('Ониши','Onishi','JPONI'),
    ('Ономичи','Onomichi','JPONO'),
    ('Оппама','Oppama','JPOPA'),
    ('Осака','Osaka','JPOSA'),
    ('Саганосеки','Saganoseki','JPSAG'),
    ('Саики','Saiki','JPSAE'),
    ('Сакаи','Sakai','JPSAK'),
    ('Сакаиде','Sakaide','JPSKD'),
    ('Сакаиминато','Sakaiminato','JPSMN'),
    ('Сакаисенбоку','Sakaisenboku','JPSBK'),
    ('Сендай, Кагосима','Sendai, Kagoshima','JPSEN'),
    ('Сендаишиогама','Sendaishiogama','JPSGM'),
    ('Сетода','Setoda','JPSTD'),
    ('Шибуши','Shibushi','JPSBS'),
    ('Шикама','Shikama','JPSKM'),
    ('Шимизу','Shimizu','JPSMZ'),
    ('Симоносеки','Shimonoseki','JPSHS'),
    ('Сукумован','Sukumowan','JPSUK'),
    ('Сусаки','Susaki','JPSUZ'),
    ('Тагоноура','Tagonoura','JPTGO'),
    ('Такамацу','Takamatsu','JPTAK'),
    ('Тобата/Китакиуши','Tobata/Kitakyushu','JPTBT'),
    ('Токио','Tokyo','JPTYO'),
    ('Томакомай','Tomakomai','JPTMK'),
    ('Тойохаси','Toyohashi','JPTHS'),
    ('Тсукуми','Tsukumi','JPTMI'),
    ('Тсунейши','Tsuneishi','JPTNI'),
    ('Убе','Ube','JPUBJ'),
    ('Вакаяма','Wakayama','JPWAK'),
    ('Яизи','Yaizu','JPYZU'),
    ('Йоккаити','Yokkaichi','JPYKK'),
    ('Йокогама','Yokohama','JPYOK'),
    ('Еура','Youra','JPYOU'),
    ('Момбаса','Mombasa','KEMBA'),
    ('Тарава','Tarawa','KITRW'),
    ('Пусан','Busan','KRPUS'),
    ('Дейсан','Daesan','KRTSN'),
    ('Гунсан','Gunsan','KRKUV'),
    ('Гванянг','Gwangyang','KRKAN'),
    ('Инчхон','Incheon','KRICH'),
    ('Джинхай','Jinhae','KRCHF'),
    ('Масан','Masan','KRMAS'),
    ('Мокпхо Апт','Mokpo Apt','KRMPK'),
    ('Онсан','Onsan','KRONA'),
    ('Пхохан','Pohang','KRKPO'),
    ('Ульсан','Ulsan','KRUSN'),
    ('Иеосу Апт','Yeosu Apt','KRRSU'),
    ('Кувейт','Kuwait','KWKWI'),
    ('Шуаиба','Shuaiba','KWSAA'),
    ('Мисурата','Misurata','LYMRA'),
    ('Бинтулу, Саравак','Bintulu, Sarawak','MYBTU'),
    ('Кертих','Kertih','MYKET'),
    ('Лабуан, Сабах','Labuan, Sabah','MYLBU'),
    ('Лахад Дату, Сабах','Lahad Datu, Sabah','MYLDU'),
    ('Мири, Sarawak','Miri, Sarawak','MYMYY'),
    ('Гасир Гуаданг, Джохор','Pasir Gudang, Johor','MYPGU'),
    ('Пинанг (Джорджтаун)','Penang (Georgetown)','MYPEN'),
    ('Порт Келанг','Port Kelang','MYPKG'),
    ('Сандакан, Сабах','Sandakan, Sabah','MYSDK'),
    ('Танджонг Пелерас','Tanjong Pelepas','MYTPP'),
    ('Маджуро','Majuro','MHMAJ'),
    ('Порт Луи','Port Louis','MUPLU'),
    ('Энсенада','Ensenada','MXESE'),
    ('Гуаймас','Guaymas','MXGYM'),
    ('Мансанильо','Manzanillo','MXZLO'),
    ('Тампико','Tampico','MXTAM'),
    ('Чуук (Truk)','Chuuk (ex Truk)','FMTKK'),
    ('Косрае (Kusaie)','Kosrae (ex Kusaie)','FMKSA'),
    ('Похнпей (Понапе)','Pohnpei (ex Ponape)','FMPNI'),
    ('Джорф Ласфар','Jorf Lasfar','MAJFL'),
    ('Лааѐун (Эль-Аюн)','Laayoune (El Aaiun)','MAEUN'),
    ('Уолфиш-Бей','Walvis Bay','NAWVB'),
    ('Роттердам','Rotterdam','NLRTM'),
    ('Курачо','Curaçao','CWCUR'),
    ('Мина'' аль Фаль','Mina'' al Fahl','OMMFH'),
    ('Бальбоа','Balboa','PABLB'),
    ('Кристобаль','Cristóbal','PACTB'),
    ('Мансанильо','Manzanillo','PAMIT'),
    ('Панама, Сиудаде','Panamá, Ciudad de','PAPTY'),
    ('Кимбе','Kimbe','PGKIM'),
    ('Кумул','Kumul','PGKUL'),
    ('Лае','Lae','PGLAE'),
    ('Лихир','Lihir Island','PGLNV'),
    ('Маданг','Madang','PGMAG'),
    ('Порт Морсби','Port Moresby','PGPOM'),
    ('Рабаул','Rabaul','PGRAB'),
    ('Байовар','Bayovar','PEPUB'),
    ('Кальяо','Callao','PECLL'),
    ('Чансай','Chancay','PECHY'),
    ('Чимботе','Chimbote','PECHM'),
    ('Паита','Paita','PEPAI'),
    ('Батангас, Лусон','Batangas, Luzon','PHBTG'),
    ('Себу','Cebu','PHCEB'),
    ('Давао, Минданао','Davao, Mindanao','PHDVO'),
    ('Генерал Сантос','General Santos','PHGES'),
    ('Манила','Manila','PHMNL'),
    ('Суал','Sual','PHSUA'),
    ('Субик Бэй','Subic Bay','PHSFS'),
    ('Лисбоа','Lisboa','PTLIS'),
    ('Сан-Хуан','San Juan','PRSJU'),
    ('Аль Шахеен','Al Shaheen','QAASN'),
    ('Доха','Doha','QADOH'),
    ('Умм Саид (Мезайед)','Umm Sa''id (Mesaieed)','QAUMS'),
    ('Samoa','Apia','WSAPW'),
    ('Джидда','Jeddah','SAJED'),
    ('Джубаил','Jubail','SAJUB'),
    ('Рас аль Хафйи','Ras al Khafji','SARAR'),
    ('Рас-Таннура','Ras Tanura','SARTA'),
    ('Янбу аль-Бахр','Yanbu al-Bahr','SAYNB'),
    ('Сингапур','Singapore','SGSIN'),
    ('Хониара, Гуадалканал','Honiara, Guadalcanal Is','SBHIR'),
    ('Норо, Нью-Джорджия','Noro, New Georgia','SBNOR'),
    ('Кейптаун','Cape Town','ZACPT'),
    ('Дурбан','Durban','ZADUR'),
    ('Ист-Лондон','East London','ZAELS'),
    ('Сеута','Ceuta','ESCEU'),
    ('Лас-Пальмас','Las Palmas','ESLPA'),
    ('Виго','Vigo','ESVGO'),
    ('Хуальен','Hualien','TWHUN'),
    ('Гаосюн','Kaohsiung','TWKHH'),
    ('Килунг (Цзилун)','Keelung (Chilung)','TWKEL'),
    ('Мэй-Лиэй','Mai-Liai','TWMAL'),
    ('Maй-Ляохэ','Mai-Liao','TWMLI'),
    ('Суао','Suao','TWSUO'),
    ('Тайчжун','Taichung','TWTXG'),
    ('Бангкок','Bangkok','THBKK'),
    ('Кох Сичанг','Koh Sichang','THKSI'),
    ('Лаим Чабанг','Laem Chabang','THLCH'),
    ('Мэб Тэпуд','Mab Tapud','THMAT'),
    ('Срирача','Sriracha','THSRI'),
    ('Кпем','Kpeme','TGKPE'),
    ('Неиафу','Neiafu','TONEI'),
    ('Нукуалофа','Nuku''alofa','TOTBU'),
    ('Сфакс','Sfax','TNSFA'),
    ('Мерсин','Mersin','TRMER'),
    ('Фунафути','Funafuti','TVFUN'),
    ('Аль Фуяырах','Al Fujayrah','AEFJR'),
    ('Дас Айлэнд','Das Island','AEDAS'),
    ('Дубай','Dubai','AEDXB'),
    ('Терминал Фатех','Fateh Terminal','AEFAT'),
    ('Джебел Дхана','Jebel Dhana','AEJED'),
    ('Хор аль Факкан','Khor al Fakkan','AEKLF'),
    ('Шарджи','Sharjah','AESHJ'),
    ('Саутгемптон','Southampton','GBSOU'),
    ('Монтевидео','Montevideo','UYMVD'),
    ('Хошимин','Ho Chi Minh City','VNSGN'),
    ('Нячанг','Nha Trang','VNNHA'),
    ('Фу Ми','Phu My','VNPHU'),
    ('Вунгтау','Vung Tau','VNVUT'),
    ('Футуна Ислэнд','Futuna Island Apt','WFFUT'),
    ('Уоллис Ислэнд','Wallis Island Apt','WFWLS'),
    ('Эш Шихр','Ash Shihr','YEASR'),
    ('Рас Аль Калиб','Ras Al Kalib','YERAK'),
    ('Паго-Паго','Pago Pago','ASPPG'),
    ('Макмердо','McMurdo','AQMCM'),
    ('Новая Земля','Terra Nova','AQTNB'),
    ('Баиа Бланка','Bahía Blanca','ARBRW'),
    ('Мар-дель-Плата','Mar del Plata','ARMDQ'),
    ('Росарио','Rosario','ARROS'),
    ('Сан-Антонио Ист','San Antonio Este','ARSAE'),
    ('Ушуая','Ushuaia','ARUSH'),
    ('Сарате','Zárate','ARZAE');