networks:
  api-server:

services:
  db:
    image: postgres:17.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=sss-computing
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../sql/:/sql/
    ports:
      - 8081:5432
    networks:
      - api-server

  api:
    build:
      context: ./api-server
      args:
        - GITHUB_TOKEN=$GITHUB_TOKEN
    ports:
      - 8080:8080
    networks:
      - api-server

  # client:
  #   build:
  #     context: ./client
  #     args:
  #       - GITHUB_TOKEN=$GITHUB_TOKEN
  #   deploy:
  #     replicas: 0
  #   environment:
  #     DISPLAY: ${DISPLAY}
  #   network_mode: host
