#!/bin/bash
# 
# Deb package postinst script for API Server
#
echo ""
systemctl daemon-reload
name="api-server"
if [[ $(systemctl list-unit-files --all -t service --full --no-legend "$name.service" | sed 's/^\s*//g' | cut -f1 -d' ') == $name.service ]]; then
    if ! systemctl is-enabled --quiet "$name.service" ; then
        echo "Enabling $name service..."
        systemctl enable api-server
    fi
    if ! systemctl is-active --quiet "$name.service" ; then
        echo "Starting $name service..."
        systemctl start api-server
    fi
else
    echo "$name service - not found"
fi
