\i ./sql/ship/ship.sql
\i ./sql/ship/center_draught.sql
\i ./sql/ship/center_waterline.sql
\i ./sql/ship/mean_draught.sql
\i ./sql/ship/pantocaren.sql
\i ./sql/ship/rad_cross.sql
\i ./sql/ship/rad_long.sql
\i ./sql/ship/flooding_angle.sql
\i ./sql/ship/entry_angle.sql
\i ./sql/loads/load_space.sql
\i ./sql/loads/load_constant.sql
\i ./sql/frames/theoretical_583.sql
\i ./sql/frames/0.sql
\i ./sql/frames/1.sql
\i ./sql/frames/2.sql
\i ./sql/frames/3.sql
\i ./sql/frames/4.sql
\i ./sql/frames/5.sql
\i ./sql/frames/6.sql
\i ./sql/frames/7.sql
\i ./sql/frames/8.sql
\i ./sql/frames/9.sql
\i ./sql/frames/10.sql
\i ./sql/frames/11.sql
\i ./sql/frames/12.sql
\i ./sql/frames/13.sql
\i ./sql/frames/14.sql
\i ./sql/frames/15.sql
\i ./sql/frames/16.sql
\i ./sql/frames/17.sql
\i ./sql/frames/18.sql
\i ./sql/frames/19.sql
\i ./sql/frames/20.sql
\i ./sql/stability/coefficient_k.sql
\i ./sql/stability/multipler_s.sql
\i ./sql/stability/multipler_x1.sql
\i ./sql/stability/multipler_x2.sql
\i ./sql/stability/navigation_area.sql
