# Markdownlint configuration
# refet to the documentation for details:
# - [Linter for markdown](https://github.com/avto-dev/markdown-lint)
# - [Rules configuration](https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml)
# - [github](https://github.com/markdownlint/markdownlint?tab=readme-ov-file)
# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md013.md
MD013:
  # Number of characters
  line_length: 160
  # Number of characters for headings
  heading_line_length: 80
  # Number of characters for code blocks
  code_block_line_length: 160
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md033.md
MD033:
    # Allowed elements
    allowed_elements: [
        details,
        summary,
    ]
  